services:
  employeemanagmentapi:
    build:
      context: .
      dockerfile: EmployeeManagmentApi/Dockerfile
    ports:
      - "5001:5000"
    environment:
      DefaultConnection: Server=employeepostgressqldb.postgres.database.azure.com;Database=EmployeesDB;Port=5432;User Id=techschool;Password=Aqaq1997914;Ssl Mode=VerifyFull;
