
POST https://localhost:7210/api/Auth/login
Content-Type: application/json

{ "username" : "hamo", "password" : "1234" }


###

GET https://localhost:7210/api/Test/authorized
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI3NWMzZGJlNC02ZmRlLTQyODktODVkMi0xNjdkZTU5NGU3NDEiLCJpYXQiOiIwNC8xMC8yMDI0IDEwLjUxLjE0IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImhhbW8iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJUZWFjaGVyIiwiRGlzcGxheU5hbWUiOiJoYW1vIiwiRW1haWwiOiJ0cm1vQHZpYS5kayIsIkFnZSI6IjM2IiwiRG9tYWluIjoidmlhIiwiU2VjdXJpdHlMZXZlbCI6IjQiLCJleHAiOjE3MjgwNDI2NzQsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.XmM5op3-1DkcHguEVEnc7tJ8vi0isyLiaOUaAQKh9xgHdaSouXWFtudqsgz7rHBKK_3Ql1QWvD0bFXf8xxtEcg