name: Build and deploy container app to Azure Web App - webapibackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: webappcontainerregistry97.azurecr.io
        username: ${{ secrets.AzureAppService_ContainerUsername_91551d0f78ea436c8a03fa83a01832b4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0d6dbf5dd8c645c9b14a25112bdaf9ca }}

    - name: Build and push container image to registry
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webapibackend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_260a120db6034ae0bdf812da6865d51d }}
        images: 'webappcontainerregistry97.azurecr.io/employeemanagmentapi:latest'
